version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: app
    networks:
      - app

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8082:8080
    networks:
      - app

  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./internal
    #     - action: rebuild
    #       path: ./pkg
    #     - action: rebuild
    #       path: ./cmd
    # ports: 
    #   - 3000:3000
    # depends_on:
    #   - postgres
    # networks:
    #   - app
      
networks:
  app:
    driver: bridge
